const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.wrap,
		C3.Behaviors.solid,
		C3.Plugins.shadowlight,
		C3.Plugins.progressbar,
		C3.Plugins.sliderbar,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.Persist,
		C3.Plugins.Button,
		C3.Plugins.HTMLElement,
		C3.Plugins.Arr,
		C3.Plugins.Date,
		C3.Behaviors.Timer,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.IsKeyCodeDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Date.Exps.FormatDateWithComponents,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsOnScreen
	];
};
self.C3_JsPropNameTable = [
	{Backround: 0},
	{Border: 0},
	{BirdsChirping: 0},
	{Notes: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{download: 0},
	{Wrap: 0},
	{Car1: 0},
	{Lvl1Backround: 0},
	{Car2: 0},
	{Cloud: 0},
	{Cloud2: 0},
	{Sprite: 0},
	{Solid: 0},
	{Sprite2: 0},
	{ShadowLight: 0},
	{EnergyBar: 0},
	{MusicBar: 0},
	{SliderBar: 0},
	{Settings: 0},
	{Sprite10: 0},
	{Sprite5: 0},
	{Particles: 0},
	{Sine: 0},
	{PlayButton: 0},
	{Player: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Tween: 0},
	{Flash: 0},
	{Player2: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{RoadBreak: 0},
	{TiledBackground: 0},
	{Title: 0},
	{Sprite12: 0},
	{Anchor: 0},
	{Persist: 0},
	{Sprite3: 0},
	{Boundry: 0},
	{DeathScreen: 0},
	{Text: 0},
	{Text2: 0},
	{Menu: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite4: 0},
	{Sprite13: 0},
	{BackButton: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Text3: 0},
	{Text4: 0},
	{Button: 0},
	{UpButtonChange: 0},
	{index: 0},
	{UpChange: 0},
	{HTMLElement: 0},
	{HowToPlayButton: 0},
	{Home: 0},
	{Done: 0},
	{Sprite18: 0},
	{LeftButtonChange: 0},
	{DownButtonChange: 0},
	{RightButtonChange: 0},
	{LeftChange: 0},
	{DownChange: 0},
	{RightChange: 0},
	{JumpButtonChange: 0},
	{JumpChange: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{PlayerSpawn: 0},
	{Sprite11: 0},
	{Water: 0},
	{Sprite21: 0},
	{bg: 0},
	{Question: 0},
	{Questions: 0},
	{A: 0},
	{B: 0},
	{C: 0},
	{D: 0},
	{Sprite23: 0},
	{CorrectWrong: 0},
	{correctwrongtext: 0},
	{Exit: 0},
	{Next: 0},
	{Date: 0},
	{Time1: 0},
	{Timer: 0},
	{TimeLeft: 0},
	{ZZZ: 0},
	{Text5: 0},
	{TargetStartScroll: 0},
	{IsJumping: 0},
	{Debug: 0},
	{Lvl2Signal: 0},
	{VarUnix: 0},
	{Health: 0},
	{WaterDamageCooldown: 0},
	{Energy: 0},
	{UpKey: 0},
	{LeftKey: 0},
	{RightKey: 0},
	{DownKey: 0},
	{JumpKey: 0},
	{UpKeyText: 0},
	{KeyPressed: 0},
	{UpChangeListening: 0},
	{LeftChangeListening: 0},
	{RightChangeListening: 0},
	{DownChangeListening: 0},
	{JumpChangeListening: 0},
	{BackClicked: 0},
	{Paused: 0},
	{QuestionAsked: 0},
	{RandomIndex: 0},
	{Correct: 0},
	{CorrectAwsnerIndex: 0},
	{ClickedAwnser: 0},
	{Clickable: 0},
	{CurrentTime: 0},
	{Signal: 0}
];

self.InstanceType = {
	Backround: class extends self.ISpriteInstance {},
	Border: class extends self.ISpriteInstance {},
	BirdsChirping: class extends self.IInstance {},
	Notes: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	download: class extends self.ISpriteInstance {},
	Car1: class extends self.ISpriteInstance {},
	Lvl1Backround: class extends self.ISpriteInstance {},
	Car2: class extends self.ISpriteInstance {},
	Cloud: class extends self.ISpriteInstance {},
	Cloud2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	EnergyBar: class extends self.IProgressBarInstance {},
	MusicBar: class extends self.ISliderBarInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	Settings: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	RoadBreak: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Title: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Boundry: class extends self.ISpriteInstance {},
	DeathScreen: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Menu: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	BackButton: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	UpButtonChange: class extends self.ISpriteInstance {},
	UpChange: class extends self.ITextInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	HowToPlayButton: class extends self.ISpriteInstance {},
	Home: class extends self.ISpriteInstance {},
	Done: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	LeftButtonChange: class extends self.ISpriteInstance {},
	DownButtonChange: class extends self.ISpriteInstance {},
	RightButtonChange: class extends self.ISpriteInstance {},
	LeftChange: class extends self.ITextInstance {},
	DownChange: class extends self.ITextInstance {},
	RightChange: class extends self.ITextInstance {},
	JumpButtonChange: class extends self.ISpriteInstance {},
	JumpChange: class extends self.ITextInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	PlayerSpawn: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	Question: class extends self.ITextInstance {},
	Questions: class extends self.IArrayInstance {},
	A: class extends self.ITextInstance {},
	B: class extends self.ITextInstance {},
	C: class extends self.ITextInstance {},
	D: class extends self.ITextInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	CorrectWrong: class extends self.ISpriteInstance {},
	correctwrongtext: class extends self.ITextInstance {},
	Exit: class extends self.ISpriteInstance {},
	Next: class extends self.ISpriteInstance {},
	Date: class extends self.IInstance {},
	Time1: class extends self.ITextInstance {},
	TimeLeft: class extends self.ITextInstance {},
	ZZZ: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {}
}